package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 25 16:45:34 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblFmrnMImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FmrnMId,
        FmpoMId,
        FmdocstsId,
        FmrnMDate,
        FmrnMDispDate,
        FmrnMRecDate,
        FmrnRemarks,
        BatchNo,
        CreditDays,
        BayId,
        CarrierId,
        GrossWeight,
        InvoiceNo,
        LocationId,
        NetWeight,
        ShortageWeight,
        Status,
        TankId,
        TearWeight,
        VehicleNo,
        VendorGrossWeight,
        VendorId,
        VendorNetWeight,
        VendorTearWeight,
        InvoiceDate,
        DeliveryNo,
        ActualFuelRecLtr,
        ActualFuelRecTon,
        ActualFuelWeighTon,
        ActualShort,
        CalorificValue,
        DipFuelShort,
        InvDensity,
        InvTempCel,
        InvTempDiff,
        InvTempFr,
        InvTotalFuelKg,
        InvTotalFuelLtr,
        InvTotalFuelTon,
        PhyDensity,
        PhyTempCel,
        PhyTempFr,
        ShortageKg,
        ShortageLtr,
        ShortageTon,
        TempShortRec,
        Viscosity,
        VolCorrFactorId,
        WaterPerc,
        VehicleInDate,
        VehicleOutDate,
        LabTemp,
        SupplierCv,
        VehicleBayIndate,
        VehicleBayOutdate,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        TblFmrnD,
        TblFmdocsts,
        TblFmpoM,
        TblFmrnDip;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FMRNMID = AttributesEnum.FmrnMId.index();
    public static final int FMPOMID = AttributesEnum.FmpoMId.index();
    public static final int FMDOCSTSID = AttributesEnum.FmdocstsId.index();
    public static final int FMRNMDATE = AttributesEnum.FmrnMDate.index();
    public static final int FMRNMDISPDATE = AttributesEnum.FmrnMDispDate.index();
    public static final int FMRNMRECDATE = AttributesEnum.FmrnMRecDate.index();
    public static final int FMRNREMARKS = AttributesEnum.FmrnRemarks.index();
    public static final int BATCHNO = AttributesEnum.BatchNo.index();
    public static final int CREDITDAYS = AttributesEnum.CreditDays.index();
    public static final int BAYID = AttributesEnum.BayId.index();
    public static final int CARRIERID = AttributesEnum.CarrierId.index();
    public static final int GROSSWEIGHT = AttributesEnum.GrossWeight.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int NETWEIGHT = AttributesEnum.NetWeight.index();
    public static final int SHORTAGEWEIGHT = AttributesEnum.ShortageWeight.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TANKID = AttributesEnum.TankId.index();
    public static final int TEARWEIGHT = AttributesEnum.TearWeight.index();
    public static final int VEHICLENO = AttributesEnum.VehicleNo.index();
    public static final int VENDORGROSSWEIGHT = AttributesEnum.VendorGrossWeight.index();
    public static final int VENDORID = AttributesEnum.VendorId.index();
    public static final int VENDORNETWEIGHT = AttributesEnum.VendorNetWeight.index();
    public static final int VENDORTEARWEIGHT = AttributesEnum.VendorTearWeight.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int DELIVERYNO = AttributesEnum.DeliveryNo.index();
    public static final int ACTUALFUELRECLTR = AttributesEnum.ActualFuelRecLtr.index();
    public static final int ACTUALFUELRECTON = AttributesEnum.ActualFuelRecTon.index();
    public static final int ACTUALFUELWEIGHTON = AttributesEnum.ActualFuelWeighTon.index();
    public static final int ACTUALSHORT = AttributesEnum.ActualShort.index();
    public static final int CALORIFICVALUE = AttributesEnum.CalorificValue.index();
    public static final int DIPFUELSHORT = AttributesEnum.DipFuelShort.index();
    public static final int INVDENSITY = AttributesEnum.InvDensity.index();
    public static final int INVTEMPCEL = AttributesEnum.InvTempCel.index();
    public static final int INVTEMPDIFF = AttributesEnum.InvTempDiff.index();
    public static final int INVTEMPFR = AttributesEnum.InvTempFr.index();
    public static final int INVTOTALFUELKG = AttributesEnum.InvTotalFuelKg.index();
    public static final int INVTOTALFUELLTR = AttributesEnum.InvTotalFuelLtr.index();
    public static final int INVTOTALFUELTON = AttributesEnum.InvTotalFuelTon.index();
    public static final int PHYDENSITY = AttributesEnum.PhyDensity.index();
    public static final int PHYTEMPCEL = AttributesEnum.PhyTempCel.index();
    public static final int PHYTEMPFR = AttributesEnum.PhyTempFr.index();
    public static final int SHORTAGEKG = AttributesEnum.ShortageKg.index();
    public static final int SHORTAGELTR = AttributesEnum.ShortageLtr.index();
    public static final int SHORTAGETON = AttributesEnum.ShortageTon.index();
    public static final int TEMPSHORTREC = AttributesEnum.TempShortRec.index();
    public static final int VISCOSITY = AttributesEnum.Viscosity.index();
    public static final int VOLCORRFACTORID = AttributesEnum.VolCorrFactorId.index();
    public static final int WATERPERC = AttributesEnum.WaterPerc.index();
    public static final int VEHICLEINDATE = AttributesEnum.VehicleInDate.index();
    public static final int VEHICLEOUTDATE = AttributesEnum.VehicleOutDate.index();
    public static final int LABTEMP = AttributesEnum.LabTemp.index();
    public static final int SUPPLIERCV = AttributesEnum.SupplierCv.index();
    public static final int VEHICLEBAYINDATE = AttributesEnum.VehicleBayIndate.index();
    public static final int VEHICLEBAYOUTDATE = AttributesEnum.VehicleBayOutdate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int TBLFMRND = AttributesEnum.TblFmrnD.index();
    public static final int TBLFMDOCSTS = AttributesEnum.TblFmdocsts.index();
    public static final int TBLFMPOM = AttributesEnum.TblFmpoM.index();
    public static final int TBLFMRNDIP = AttributesEnum.TblFmrnDip.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblFmrnMImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblFmrnM");
    }


    /**
     * Gets the attribute value for FmrnMId, using the alias name FmrnMId.
     * @return the value of FmrnMId
     */
    public BigDecimal getFmrnMId() {
        return (BigDecimal) getAttributeInternal(FMRNMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmrnMId.
     * @param value value to set the FmrnMId
     */
    public void setFmrnMId(BigDecimal value) {
        setAttributeInternal(FMRNMID, value);
    }

    /**
     * Gets the attribute value for FmpoMId, using the alias name FmpoMId.
     * @return the value of FmpoMId
     */
    public BigDecimal getFmpoMId() {
        return (BigDecimal) getAttributeInternal(FMPOMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmpoMId.
     * @param value value to set the FmpoMId
     */
    public void setFmpoMId(BigDecimal value) {
        setAttributeInternal(FMPOMID, value);
    }

    /**
     * Gets the attribute value for FmdocstsId, using the alias name FmdocstsId.
     * @return the value of FmdocstsId
     */
    public BigDecimal getFmdocstsId() {
        return (BigDecimal) getAttributeInternal(FMDOCSTSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmdocstsId.
     * @param value value to set the FmdocstsId
     */
    public void setFmdocstsId(BigDecimal value) {
        setAttributeInternal(FMDOCSTSID, value);
    }

    /**
     * Gets the attribute value for FmrnMDate, using the alias name FmrnMDate.
     * @return the value of FmrnMDate
     */
    public Timestamp getFmrnMDate() {
        return (Timestamp) getAttributeInternal(FMRNMDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmrnMDate.
     * @param value value to set the FmrnMDate
     */
    public void setFmrnMDate(Timestamp value) {
        setAttributeInternal(FMRNMDATE, value);
    }

    /**
     * Gets the attribute value for FmrnMDispDate, using the alias name FmrnMDispDate.
     * @return the value of FmrnMDispDate
     */
    public Timestamp getFmrnMDispDate() {
        return (Timestamp) getAttributeInternal(FMRNMDISPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmrnMDispDate.
     * @param value value to set the FmrnMDispDate
     */
    public void setFmrnMDispDate(Timestamp value) {
        setAttributeInternal(FMRNMDISPDATE, value);
    }

    /**
     * Gets the attribute value for FmrnMRecDate, using the alias name FmrnMRecDate.
     * @return the value of FmrnMRecDate
     */
    public Timestamp getFmrnMRecDate() {
        return (Timestamp) getAttributeInternal(FMRNMRECDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmrnMRecDate.
     * @param value value to set the FmrnMRecDate
     */
    public void setFmrnMRecDate(Timestamp value) {
        setAttributeInternal(FMRNMRECDATE, value);
    }

    /**
     * Gets the attribute value for FmrnRemarks, using the alias name FmrnRemarks.
     * @return the value of FmrnRemarks
     */
    public String getFmrnRemarks() {
        return (String) getAttributeInternal(FMRNREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmrnRemarks.
     * @param value value to set the FmrnRemarks
     */
    public void setFmrnRemarks(String value) {
        setAttributeInternal(FMRNREMARKS, value);
    }

    /**
     * Gets the attribute value for BatchNo, using the alias name BatchNo.
     * @return the value of BatchNo
     */
    public String getBatchNo() {
        return (String) getAttributeInternal(BATCHNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchNo.
     * @param value value to set the BatchNo
     */
    public void setBatchNo(String value) {
        setAttributeInternal(BATCHNO, value);
    }

    /**
     * Gets the attribute value for CreditDays, using the alias name CreditDays.
     * @return the value of CreditDays
     */
    public BigDecimal getCreditDays() {
        return (BigDecimal) getAttributeInternal(CREDITDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditDays.
     * @param value value to set the CreditDays
     */
    public void setCreditDays(BigDecimal value) {
        setAttributeInternal(CREDITDAYS, value);
    }

    /**
     * Gets the attribute value for BayId, using the alias name BayId.
     * @return the value of BayId
     */
    public BigDecimal getBayId() {
        return (BigDecimal) getAttributeInternal(BAYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BayId.
     * @param value value to set the BayId
     */
    public void setBayId(BigDecimal value) {
        setAttributeInternal(BAYID, value);
    }

    /**
     * Gets the attribute value for CarrierId, using the alias name CarrierId.
     * @return the value of CarrierId
     */
    public BigDecimal getCarrierId() {
        return (BigDecimal) getAttributeInternal(CARRIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CarrierId.
     * @param value value to set the CarrierId
     */
    public void setCarrierId(BigDecimal value) {
        setAttributeInternal(CARRIERID, value);
    }

    /**
     * Gets the attribute value for GrossWeight, using the alias name GrossWeight.
     * @return the value of GrossWeight
     */
    public BigDecimal getGrossWeight() {
        return (BigDecimal) getAttributeInternal(GROSSWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrossWeight.
     * @param value value to set the GrossWeight
     */
    public void setGrossWeight(BigDecimal value) {
        setAttributeInternal(GROSSWEIGHT, value);
    }

    /**
     * Gets the attribute value for InvoiceNo, using the alias name InvoiceNo.
     * @return the value of InvoiceNo
     */
    public String getInvoiceNo() {
        return (String) getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceNo.
     * @param value value to set the InvoiceNo
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for LocationId, using the alias name LocationId.
     * @return the value of LocationId
     */
    public BigDecimal getLocationId() {
        return (BigDecimal) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationId.
     * @param value value to set the LocationId
     */
    public void setLocationId(BigDecimal value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for NetWeight, using the alias name NetWeight.
     * @return the value of NetWeight
     */
    public BigDecimal getNetWeight() {
        return (BigDecimal) getAttributeInternal(NETWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetWeight.
     * @param value value to set the NetWeight
     */
    public void setNetWeight(BigDecimal value) {
        setAttributeInternal(NETWEIGHT, value);
    }

    /**
     * Gets the attribute value for ShortageWeight, using the alias name ShortageWeight.
     * @return the value of ShortageWeight
     */
    public BigDecimal getShortageWeight() {
        return (BigDecimal) getAttributeInternal(SHORTAGEWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShortageWeight.
     * @param value value to set the ShortageWeight
     */
    public void setShortageWeight(BigDecimal value) {
        setAttributeInternal(SHORTAGEWEIGHT, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for TankId, using the alias name TankId.
     * @return the value of TankId
     */
    public BigDecimal getTankId() {
        return (BigDecimal) getAttributeInternal(TANKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TankId.
     * @param value value to set the TankId
     */
    public void setTankId(BigDecimal value) {
        setAttributeInternal(TANKID, value);
    }

    /**
     * Gets the attribute value for TearWeight, using the alias name TearWeight.
     * @return the value of TearWeight
     */
    public BigDecimal getTearWeight() {
        return (BigDecimal) getAttributeInternal(TEARWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TearWeight.
     * @param value value to set the TearWeight
     */
    public void setTearWeight(BigDecimal value) {
        setAttributeInternal(TEARWEIGHT, value);
    }

    /**
     * Gets the attribute value for VehicleNo, using the alias name VehicleNo.
     * @return the value of VehicleNo
     */
    public String getVehicleNo() {
        return (String) getAttributeInternal(VEHICLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleNo.
     * @param value value to set the VehicleNo
     */
    public void setVehicleNo(String value) {
        setAttributeInternal(VEHICLENO, value);
    }

    /**
     * Gets the attribute value for VendorGrossWeight, using the alias name VendorGrossWeight.
     * @return the value of VendorGrossWeight
     */
    public BigDecimal getVendorGrossWeight() {
        return (BigDecimal) getAttributeInternal(VENDORGROSSWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorGrossWeight.
     * @param value value to set the VendorGrossWeight
     */
    public void setVendorGrossWeight(BigDecimal value) {
        setAttributeInternal(VENDORGROSSWEIGHT, value);
    }

    /**
     * Gets the attribute value for VendorId, using the alias name VendorId.
     * @return the value of VendorId
     */
    public BigDecimal getVendorId() {
        return (BigDecimal) getAttributeInternal(VENDORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorId.
     * @param value value to set the VendorId
     */
    public void setVendorId(BigDecimal value) {
        setAttributeInternal(VENDORID, value);
    }

    /**
     * Gets the attribute value for VendorNetWeight, using the alias name VendorNetWeight.
     * @return the value of VendorNetWeight
     */
    public BigDecimal getVendorNetWeight() {
        return (BigDecimal) getAttributeInternal(VENDORNETWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorNetWeight.
     * @param value value to set the VendorNetWeight
     */
    public void setVendorNetWeight(BigDecimal value) {
        setAttributeInternal(VENDORNETWEIGHT, value);
    }

    /**
     * Gets the attribute value for VendorTearWeight, using the alias name VendorTearWeight.
     * @return the value of VendorTearWeight
     */
    public BigDecimal getVendorTearWeight() {
        return (BigDecimal) getAttributeInternal(VENDORTEARWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorTearWeight.
     * @param value value to set the VendorTearWeight
     */
    public void setVendorTearWeight(BigDecimal value) {
        setAttributeInternal(VENDORTEARWEIGHT, value);
    }

    /**
     * Gets the attribute value for InvoiceDate, using the alias name InvoiceDate.
     * @return the value of InvoiceDate
     */
    public Timestamp getInvoiceDate() {
        return (Timestamp) getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceDate.
     * @param value value to set the InvoiceDate
     */
    public void setInvoiceDate(Timestamp value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for DeliveryNo, using the alias name DeliveryNo.
     * @return the value of DeliveryNo
     */
    public BigDecimal getDeliveryNo() {
        return (BigDecimal) getAttributeInternal(DELIVERYNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryNo.
     * @param value value to set the DeliveryNo
     */
    public void setDeliveryNo(BigDecimal value) {
        setAttributeInternal(DELIVERYNO, value);
    }

    /**
     * Gets the attribute value for ActualFuelRecLtr, using the alias name ActualFuelRecLtr.
     * @return the value of ActualFuelRecLtr
     */
    public BigDecimal getActualFuelRecLtr() {
        return (BigDecimal) getAttributeInternal(ACTUALFUELRECLTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualFuelRecLtr.
     * @param value value to set the ActualFuelRecLtr
     */
    public void setActualFuelRecLtr(BigDecimal value) {
        setAttributeInternal(ACTUALFUELRECLTR, value);
    }

    /**
     * Gets the attribute value for ActualFuelRecTon, using the alias name ActualFuelRecTon.
     * @return the value of ActualFuelRecTon
     */
    public BigDecimal getActualFuelRecTon() {
        return (BigDecimal) getAttributeInternal(ACTUALFUELRECTON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualFuelRecTon.
     * @param value value to set the ActualFuelRecTon
     */
    public void setActualFuelRecTon(BigDecimal value) {
        setAttributeInternal(ACTUALFUELRECTON, value);
    }

    /**
     * Gets the attribute value for ActualFuelWeighTon, using the alias name ActualFuelWeighTon.
     * @return the value of ActualFuelWeighTon
     */
    public BigDecimal getActualFuelWeighTon() {
        return (BigDecimal) getAttributeInternal(ACTUALFUELWEIGHTON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualFuelWeighTon.
     * @param value value to set the ActualFuelWeighTon
     */
    public void setActualFuelWeighTon(BigDecimal value) {
        setAttributeInternal(ACTUALFUELWEIGHTON, value);
    }

    /**
     * Gets the attribute value for ActualShort, using the alias name ActualShort.
     * @return the value of ActualShort
     */
    public BigDecimal getActualShort() {
        return (BigDecimal) getAttributeInternal(ACTUALSHORT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualShort.
     * @param value value to set the ActualShort
     */
    public void setActualShort(BigDecimal value) {
        setAttributeInternal(ACTUALSHORT, value);
    }

    /**
     * Gets the attribute value for CalorificValue, using the alias name CalorificValue.
     * @return the value of CalorificValue
     */
    public BigDecimal getCalorificValue() {
        return (BigDecimal) getAttributeInternal(CALORIFICVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CalorificValue.
     * @param value value to set the CalorificValue
     */
    public void setCalorificValue(BigDecimal value) {
        setAttributeInternal(CALORIFICVALUE, value);
    }

    /**
     * Gets the attribute value for DipFuelShort, using the alias name DipFuelShort.
     * @return the value of DipFuelShort
     */
    public BigDecimal getDipFuelShort() {
        return (BigDecimal) getAttributeInternal(DIPFUELSHORT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DipFuelShort.
     * @param value value to set the DipFuelShort
     */
    public void setDipFuelShort(BigDecimal value) {
        setAttributeInternal(DIPFUELSHORT, value);
    }

    /**
     * Gets the attribute value for InvDensity, using the alias name InvDensity.
     * @return the value of InvDensity
     */
    public BigDecimal getInvDensity() {
        return (BigDecimal) getAttributeInternal(INVDENSITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvDensity.
     * @param value value to set the InvDensity
     */
    public void setInvDensity(BigDecimal value) {
        setAttributeInternal(INVDENSITY, value);
    }

    /**
     * Gets the attribute value for InvTempCel, using the alias name InvTempCel.
     * @return the value of InvTempCel
     */
    public BigDecimal getInvTempCel() {
        return (BigDecimal) getAttributeInternal(INVTEMPCEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvTempCel.
     * @param value value to set the InvTempCel
     */
    public void setInvTempCel(BigDecimal value) {
        setAttributeInternal(INVTEMPCEL, value);
    }

    /**
     * Gets the attribute value for InvTempDiff, using the alias name InvTempDiff.
     * @return the value of InvTempDiff
     */
    public BigDecimal getInvTempDiff() {
        return (BigDecimal) getAttributeInternal(INVTEMPDIFF);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvTempDiff.
     * @param value value to set the InvTempDiff
     */
    public void setInvTempDiff(BigDecimal value) {
        setAttributeInternal(INVTEMPDIFF, value);
    }

    /**
     * Gets the attribute value for InvTempFr, using the alias name InvTempFr.
     * @return the value of InvTempFr
     */
    public BigDecimal getInvTempFr() {
        return (BigDecimal) getAttributeInternal(INVTEMPFR);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvTempFr.
     * @param value value to set the InvTempFr
     */
    public void setInvTempFr(BigDecimal value) {
        setAttributeInternal(INVTEMPFR, value);
    }

    /**
     * Gets the attribute value for InvTotalFuelKg, using the alias name InvTotalFuelKg.
     * @return the value of InvTotalFuelKg
     */
    public BigDecimal getInvTotalFuelKg() {
        return (BigDecimal) getAttributeInternal(INVTOTALFUELKG);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvTotalFuelKg.
     * @param value value to set the InvTotalFuelKg
     */
    public void setInvTotalFuelKg(BigDecimal value) {
        setAttributeInternal(INVTOTALFUELKG, value);
    }

    /**
     * Gets the attribute value for InvTotalFuelLtr, using the alias name InvTotalFuelLtr.
     * @return the value of InvTotalFuelLtr
     */
    public BigDecimal getInvTotalFuelLtr() {
        return (BigDecimal) getAttributeInternal(INVTOTALFUELLTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvTotalFuelLtr.
     * @param value value to set the InvTotalFuelLtr
     */
    public void setInvTotalFuelLtr(BigDecimal value) {
        setAttributeInternal(INVTOTALFUELLTR, value);
    }

    /**
     * Gets the attribute value for InvTotalFuelTon, using the alias name InvTotalFuelTon.
     * @return the value of InvTotalFuelTon
     */
    public BigDecimal getInvTotalFuelTon() {
        return (BigDecimal) getAttributeInternal(INVTOTALFUELTON);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvTotalFuelTon.
     * @param value value to set the InvTotalFuelTon
     */
    public void setInvTotalFuelTon(BigDecimal value) {
        setAttributeInternal(INVTOTALFUELTON, value);
    }

    /**
     * Gets the attribute value for PhyDensity, using the alias name PhyDensity.
     * @return the value of PhyDensity
     */
    public BigDecimal getPhyDensity() {
        return (BigDecimal) getAttributeInternal(PHYDENSITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhyDensity.
     * @param value value to set the PhyDensity
     */
    public void setPhyDensity(BigDecimal value) {
        setAttributeInternal(PHYDENSITY, value);
    }

    /**
     * Gets the attribute value for PhyTempCel, using the alias name PhyTempCel.
     * @return the value of PhyTempCel
     */
    public BigDecimal getPhyTempCel() {
        return (BigDecimal) getAttributeInternal(PHYTEMPCEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhyTempCel.
     * @param value value to set the PhyTempCel
     */
    public void setPhyTempCel(BigDecimal value) {
        setAttributeInternal(PHYTEMPCEL, value);
    }

    /**
     * Gets the attribute value for PhyTempFr, using the alias name PhyTempFr.
     * @return the value of PhyTempFr
     */
    public BigDecimal getPhyTempFr() {
        return (BigDecimal) getAttributeInternal(PHYTEMPFR);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhyTempFr.
     * @param value value to set the PhyTempFr
     */
    public void setPhyTempFr(BigDecimal value) {
        setAttributeInternal(PHYTEMPFR, value);
    }

    /**
     * Gets the attribute value for ShortageKg, using the alias name ShortageKg.
     * @return the value of ShortageKg
     */
    public BigDecimal getShortageKg() {
        return (BigDecimal) getAttributeInternal(SHORTAGEKG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShortageKg.
     * @param value value to set the ShortageKg
     */
    public void setShortageKg(BigDecimal value) {
        setAttributeInternal(SHORTAGEKG, value);
    }

    /**
     * Gets the attribute value for ShortageLtr, using the alias name ShortageLtr.
     * @return the value of ShortageLtr
     */
    public BigDecimal getShortageLtr() {
        return (BigDecimal) getAttributeInternal(SHORTAGELTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShortageLtr.
     * @param value value to set the ShortageLtr
     */
    public void setShortageLtr(BigDecimal value) {
        setAttributeInternal(SHORTAGELTR, value);
    }

    /**
     * Gets the attribute value for ShortageTon, using the alias name ShortageTon.
     * @return the value of ShortageTon
     */
    public BigDecimal getShortageTon() {
        return (BigDecimal) getAttributeInternal(SHORTAGETON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShortageTon.
     * @param value value to set the ShortageTon
     */
    public void setShortageTon(BigDecimal value) {
        setAttributeInternal(SHORTAGETON, value);
    }

    /**
     * Gets the attribute value for TempShortRec, using the alias name TempShortRec.
     * @return the value of TempShortRec
     */
    public BigDecimal getTempShortRec() {
        return (BigDecimal) getAttributeInternal(TEMPSHORTREC);
    }

    /**
     * Sets <code>value</code> as the attribute value for TempShortRec.
     * @param value value to set the TempShortRec
     */
    public void setTempShortRec(BigDecimal value) {
        setAttributeInternal(TEMPSHORTREC, value);
    }

    /**
     * Gets the attribute value for Viscosity, using the alias name Viscosity.
     * @return the value of Viscosity
     */
    public BigDecimal getViscosity() {
        return (BigDecimal) getAttributeInternal(VISCOSITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Viscosity.
     * @param value value to set the Viscosity
     */
    public void setViscosity(BigDecimal value) {
        setAttributeInternal(VISCOSITY, value);
    }

    /**
     * Gets the attribute value for VolCorrFactorId, using the alias name VolCorrFactorId.
     * @return the value of VolCorrFactorId
     */
    public Number getVolCorrFactorId() {
        return (Number) getAttributeInternal(VOLCORRFACTORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VolCorrFactorId.
     * @param value value to set the VolCorrFactorId
     */
    public void setVolCorrFactorId(Number value) {
        setAttributeInternal(VOLCORRFACTORID, value);
    }

    /**
     * Gets the attribute value for WaterPerc, using the alias name WaterPerc.
     * @return the value of WaterPerc
     */
    public BigDecimal getWaterPerc() {
        return (BigDecimal) getAttributeInternal(WATERPERC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WaterPerc.
     * @param value value to set the WaterPerc
     */
    public void setWaterPerc(BigDecimal value) {
        setAttributeInternal(WATERPERC, value);
    }

    /**
     * Gets the attribute value for VehicleInDate, using the alias name VehicleInDate.
     * @return the value of VehicleInDate
     */
    public Timestamp getVehicleInDate() {
        return (Timestamp) getAttributeInternal(VEHICLEINDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleInDate.
     * @param value value to set the VehicleInDate
     */
    public void setVehicleInDate(Timestamp value) {
        setAttributeInternal(VEHICLEINDATE, value);
    }

    /**
     * Gets the attribute value for VehicleOutDate, using the alias name VehicleOutDate.
     * @return the value of VehicleOutDate
     */
    public Timestamp getVehicleOutDate() {
        return (Timestamp) getAttributeInternal(VEHICLEOUTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleOutDate.
     * @param value value to set the VehicleOutDate
     */
    public void setVehicleOutDate(Timestamp value) {
        setAttributeInternal(VEHICLEOUTDATE, value);
    }

    /**
     * Gets the attribute value for LabTemp, using the alias name LabTemp.
     * @return the value of LabTemp
     */
    public BigDecimal getLabTemp() {
        return (BigDecimal) getAttributeInternal(LABTEMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for LabTemp.
     * @param value value to set the LabTemp
     */
    public void setLabTemp(BigDecimal value) {
        setAttributeInternal(LABTEMP, value);
    }

    /**
     * Gets the attribute value for SupplierCv, using the alias name SupplierCv.
     * @return the value of SupplierCv
     */
    public BigDecimal getSupplierCv() {
        return (BigDecimal) getAttributeInternal(SUPPLIERCV);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierCv.
     * @param value value to set the SupplierCv
     */
    public void setSupplierCv(BigDecimal value) {
        setAttributeInternal(SUPPLIERCV, value);
    }

    /**
     * Gets the attribute value for VehicleBayIndate, using the alias name VehicleBayIndate.
     * @return the value of VehicleBayIndate
     */
    public Timestamp getVehicleBayIndate() {
        return (Timestamp) getAttributeInternal(VEHICLEBAYINDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleBayIndate.
     * @param value value to set the VehicleBayIndate
     */
    public void setVehicleBayIndate(Timestamp value) {
        setAttributeInternal(VEHICLEBAYINDATE, value);
    }

    /**
     * Gets the attribute value for VehicleBayOutdate, using the alias name VehicleBayOutdate.
     * @return the value of VehicleBayOutdate
     */
    public Timestamp getVehicleBayOutdate() {
        return (Timestamp) getAttributeInternal(VEHICLEBAYOUTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleBayOutdate.
     * @param value value to set the VehicleBayOutdate
     */
    public void setVehicleBayOutdate(Timestamp value) {
        setAttributeInternal(VEHICLEBAYOUTDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblFmrnD() {
        return (RowIterator) getAttributeInternal(TBLFMRND);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTblFmdocsts() {
        return (EntityImpl) getAttributeInternal(TBLFMDOCSTS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTblFmdocsts(EntityImpl value) {
        setAttributeInternal(TBLFMDOCSTS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTblFmpoM() {
        return (EntityImpl) getAttributeInternal(TBLFMPOM);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTblFmpoM(EntityImpl value) {
        setAttributeInternal(TBLFMPOM, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblFmrnDip() {
        return (RowIterator) getAttributeInternal(TBLFMRNDIP);
    }


    /**
     * @param fmrnMId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal fmrnMId) {
        return new Key(new Object[] { fmrnMId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
                try {
                    loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
                } catch(Exception ex) {
                    ex.printStackTrace();
                }
                
                if (operation == DML_INSERT) {
                    setCreatedBy(loginId);
                    setUpdatedBy(loginId);
                    } else if(operation == DML_UPDATE) {
                    setUpdatedBy(loginId);
                }
        super.doDML(operation, e);
    }
}

