package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 12:29:05 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblFmtokenImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FmtokenId,
        FmtokenDate,
        FmtokenVehicleNo,
        FmtokenRemarks,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        TblFmigp;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FMTOKENID = AttributesEnum.FmtokenId.index();
    public static final int FMTOKENDATE = AttributesEnum.FmtokenDate.index();
    public static final int FMTOKENVEHICLENO = AttributesEnum.FmtokenVehicleNo.index();
    public static final int FMTOKENREMARKS = AttributesEnum.FmtokenRemarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int TBLFMIGP = AttributesEnum.TblFmigp.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblFmtokenImpl() {
    }

    /**
     * Gets the attribute value for FmtokenId, using the alias name FmtokenId.
     * @return the value of FmtokenId
     */
    public BigDecimal getFmtokenId() {
        return (BigDecimal) getAttributeInternal(FMTOKENID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmtokenId.
     * @param value value to set the FmtokenId
     */
    public void setFmtokenId(BigDecimal value) {
        setAttributeInternal(FMTOKENID, value);
    }

    /**
     * Gets the attribute value for FmtokenDate, using the alias name FmtokenDate.
     * @return the value of FmtokenDate
     */
    public Timestamp getFmtokenDate() {
        return (Timestamp) getAttributeInternal(FMTOKENDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmtokenDate.
     * @param value value to set the FmtokenDate
     */
    public void setFmtokenDate(Timestamp value) {
        setAttributeInternal(FMTOKENDATE, value);
    }

    /**
     * Gets the attribute value for FmtokenVehicleNo, using the alias name FmtokenVehicleNo.
     * @return the value of FmtokenVehicleNo
     */
    public String getFmtokenVehicleNo() {
        return (String) getAttributeInternal(FMTOKENVEHICLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmtokenVehicleNo.
     * @param value value to set the FmtokenVehicleNo
     */
    public void setFmtokenVehicleNo(String value) {
        setAttributeInternal(FMTOKENVEHICLENO, value);
    }

    /**
     * Gets the attribute value for FmtokenRemarks, using the alias name FmtokenRemarks.
     * @return the value of FmtokenRemarks
     */
    public String getFmtokenRemarks() {
        return (String) getAttributeInternal(FMTOKENREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmtokenRemarks.
     * @param value value to set the FmtokenRemarks
     */
    public void setFmtokenRemarks(String value) {
        setAttributeInternal(FMTOKENREMARKS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblFmigp() {
        return (RowIterator) getAttributeInternal(TBLFMIGP);
    }

    /**
     * @param fmtokenId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal fmtokenId) {
        return new Key(new Object[] { fmtokenId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblFmtoken");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
             try {
                 loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
             } catch(Exception ex) {
                 ex.printStackTrace();
             }
             
             if (operation == DML_INSERT) {
                 setCreatedBy(loginId);
                 setUpdatedBy(loginId);
                 } else if(operation == DML_UPDATE) {
                 setUpdatedBy(loginId);
             }
        super.doDML(operation, e);
    }
}

