package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 11:20:46 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblFmcarrierImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FmcarrierId,
        FmcarrierName,
        Ast,
        FmcarrierCper,
        FmcarrierDsg,
        FmcarrierAdrs,
        FmcarrierPhone,
        FmcarrierMob,
        FmcarrierNtn,
        FmcarrierStrn,
        FmcarrierCrl,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FMCARRIERID = AttributesEnum.FmcarrierId.index();
    public static final int FMCARRIERNAME = AttributesEnum.FmcarrierName.index();
    public static final int AST = AttributesEnum.Ast.index();
    public static final int FMCARRIERCPER = AttributesEnum.FmcarrierCper.index();
    public static final int FMCARRIERDSG = AttributesEnum.FmcarrierDsg.index();
    public static final int FMCARRIERADRS = AttributesEnum.FmcarrierAdrs.index();
    public static final int FMCARRIERPHONE = AttributesEnum.FmcarrierPhone.index();
    public static final int FMCARRIERMOB = AttributesEnum.FmcarrierMob.index();
    public static final int FMCARRIERNTN = AttributesEnum.FmcarrierNtn.index();
    public static final int FMCARRIERSTRN = AttributesEnum.FmcarrierStrn.index();
    public static final int FMCARRIERCRL = AttributesEnum.FmcarrierCrl.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblFmcarrierImpl() {
    }

    /**
     * Gets the attribute value for FmcarrierId, using the alias name FmcarrierId.
     * @return the value of FmcarrierId
     */
    public BigDecimal getFmcarrierId() {
        return (BigDecimal) getAttributeInternal(FMCARRIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierId.
     * @param value value to set the FmcarrierId
     */
    public void setFmcarrierId(BigDecimal value) {
        setAttributeInternal(FMCARRIERID, value);
    }

    /**
     * Gets the attribute value for FmcarrierName, using the alias name FmcarrierName.
     * @return the value of FmcarrierName
     */
    public String getFmcarrierName() {
        return (String) getAttributeInternal(FMCARRIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierName.
     * @param value value to set the FmcarrierName
     */
    public void setFmcarrierName(String value) {
        setAttributeInternal(FMCARRIERNAME, value);
    }

    /**
     * Gets the attribute value for Ast, using the alias name Ast.
     * @return the value of Ast
     */
    public String getAst() {
        return (String) getAttributeInternal(AST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ast.
     * @param value value to set the Ast
     */
    public void setAst(String value) {
        setAttributeInternal(AST, value);
    }

    /**
     * Gets the attribute value for FmcarrierCper, using the alias name FmcarrierCper.
     * @return the value of FmcarrierCper
     */
    public String getFmcarrierCper() {
        return (String) getAttributeInternal(FMCARRIERCPER);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierCper.
     * @param value value to set the FmcarrierCper
     */
    public void setFmcarrierCper(String value) {
        setAttributeInternal(FMCARRIERCPER, value);
    }

    /**
     * Gets the attribute value for FmcarrierDsg, using the alias name FmcarrierDsg.
     * @return the value of FmcarrierDsg
     */
    public String getFmcarrierDsg() {
        return (String) getAttributeInternal(FMCARRIERDSG);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierDsg.
     * @param value value to set the FmcarrierDsg
     */
    public void setFmcarrierDsg(String value) {
        setAttributeInternal(FMCARRIERDSG, value);
    }

    /**
     * Gets the attribute value for FmcarrierAdrs, using the alias name FmcarrierAdrs.
     * @return the value of FmcarrierAdrs
     */
    public String getFmcarrierAdrs() {
        return (String) getAttributeInternal(FMCARRIERADRS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierAdrs.
     * @param value value to set the FmcarrierAdrs
     */
    public void setFmcarrierAdrs(String value) {
        setAttributeInternal(FMCARRIERADRS, value);
    }

    /**
     * Gets the attribute value for FmcarrierPhone, using the alias name FmcarrierPhone.
     * @return the value of FmcarrierPhone
     */
    public String getFmcarrierPhone() {
        return (String) getAttributeInternal(FMCARRIERPHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierPhone.
     * @param value value to set the FmcarrierPhone
     */
    public void setFmcarrierPhone(String value) {
        setAttributeInternal(FMCARRIERPHONE, value);
    }

    /**
     * Gets the attribute value for FmcarrierMob, using the alias name FmcarrierMob.
     * @return the value of FmcarrierMob
     */
    public String getFmcarrierMob() {
        return (String) getAttributeInternal(FMCARRIERMOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierMob.
     * @param value value to set the FmcarrierMob
     */
    public void setFmcarrierMob(String value) {
        setAttributeInternal(FMCARRIERMOB, value);
    }

    /**
     * Gets the attribute value for FmcarrierNtn, using the alias name FmcarrierNtn.
     * @return the value of FmcarrierNtn
     */
    public String getFmcarrierNtn() {
        return (String) getAttributeInternal(FMCARRIERNTN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierNtn.
     * @param value value to set the FmcarrierNtn
     */
    public void setFmcarrierNtn(String value) {
        setAttributeInternal(FMCARRIERNTN, value);
    }

    /**
     * Gets the attribute value for FmcarrierStrn, using the alias name FmcarrierStrn.
     * @return the value of FmcarrierStrn
     */
    public String getFmcarrierStrn() {
        return (String) getAttributeInternal(FMCARRIERSTRN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierStrn.
     * @param value value to set the FmcarrierStrn
     */
    public void setFmcarrierStrn(String value) {
        setAttributeInternal(FMCARRIERSTRN, value);
    }

    /**
     * Gets the attribute value for FmcarrierCrl, using the alias name FmcarrierCrl.
     * @return the value of FmcarrierCrl
     */
    public String getFmcarrierCrl() {
        return (String) getAttributeInternal(FMCARRIERCRL);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmcarrierCrl.
     * @param value value to set the FmcarrierCrl
     */
    public void setFmcarrierCrl(String value) {
        setAttributeInternal(FMCARRIERCRL, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @param fmcarrierId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal fmcarrierId) {
        return new Key(new Object[] { fmcarrierId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblFmcarrier");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
             try {
                 loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessUMID"));
             } catch(Exception ex) {
                 ex.printStackTrace();
             }
             
             if (operation == DML_INSERT) {
                 setCreatedBy(loginId);
                 setUpdatedBy(loginId);
                 } else if(operation == DML_UPDATE) {
                 setUpdatedBy(loginId);
             }
        super.doDML(operation, e);
    }
}

