package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 12:34:05 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblFmvcfImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FmvcfId,
        FromValue,
        ToValue,
        VcfValue,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FMVCFID = AttributesEnum.FmvcfId.index();
    public static final int FROMVALUE = AttributesEnum.FromValue.index();
    public static final int TOVALUE = AttributesEnum.ToValue.index();
    public static final int VCFVALUE = AttributesEnum.VcfValue.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblFmvcfImpl() {
    }

    /**
     * Gets the attribute value for FmvcfId, using the alias name FmvcfId.
     * @return the value of FmvcfId
     */
    public BigDecimal getFmvcfId() {
        return (BigDecimal) getAttributeInternal(FMVCFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FmvcfId.
     * @param value value to set the FmvcfId
     */
    public void setFmvcfId(BigDecimal value) {
        setAttributeInternal(FMVCFID, value);
    }

    /**
     * Gets the attribute value for FromValue, using the alias name FromValue.
     * @return the value of FromValue
     */
    public BigDecimal getFromValue() {
        return (BigDecimal) getAttributeInternal(FROMVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromValue.
     * @param value value to set the FromValue
     */
    public void setFromValue(BigDecimal value) {
        setAttributeInternal(FROMVALUE, value);
    }

    /**
     * Gets the attribute value for ToValue, using the alias name ToValue.
     * @return the value of ToValue
     */
    public BigDecimal getToValue() {
        return (BigDecimal) getAttributeInternal(TOVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToValue.
     * @param value value to set the ToValue
     */
    public void setToValue(BigDecimal value) {
        setAttributeInternal(TOVALUE, value);
    }

    /**
     * Gets the attribute value for VcfValue, using the alias name VcfValue.
     * @return the value of VcfValue
     */
    public BigDecimal getVcfValue() {
        return (BigDecimal) getAttributeInternal(VCFVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VcfValue.
     * @param value value to set the VcfValue
     */
    public void setVcfValue(BigDecimal value) {
        setAttributeInternal(VCFVALUE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @param fmvcfId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal fmvcfId) {
        return new Key(new Object[] { fmvcfId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblFmvcf");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
             try {
                 loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
             } catch(Exception ex) {
                 ex.printStackTrace();
             }
             
             if (operation == DML_INSERT) {
                 setCreatedBy(loginId);
                 setUpdatedBy(loginId);
                 } else if(operation == DML_UPDATE) {
                 setUpdatedBy(loginId);
             }
        super.doDML(operation, e);
    }
}

